/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      colors: {
        primary: {
          DEFAULT: '#AD2C4E',
          50: '#FDF4F6',
          100: '#FCE8EC',
          200: '#F9D1D9',
          300: '#F4AFC0',
          400: '#EB7A95',
          500: '#AD2C4E',
          600: '#8B2340',
          700: '#6B1C33',
          800: '#4B1526',
          900: '#2B0F19',
        },
        secondary: {
          DEFAULT: '#934656',
        },
        accent: {
          DEFAULT: '#BA1340',
        },
        background: '#FCF9F8',
        surface: '#FFFFFF',
        text: '#1B1C1C',
        error: '#BA1A1A',
        success: '#27AE60',
        border: {
          input: '#FF9EAF',
        },
        'primary-container': '#ff6b8a',
        'on-primary': '#ffffff',
        'on-surface': '#1b1c1c',
        'on-surface-variant': '#574144',
        'surface-container-lowest': '#ffffff',
        'primary-fixed-dim': '#ffb2bd',
        'secondary-container': '#FFD9E1',
        'on-secondary-container': '#3A0817',
        'secondary-fixed': '#FFD9E1',
        tertiary: '#8B5E00',
        'tertiary-container': '#FFDEA6',
        'on-tertiary-container': '#2B1B00',
        'tertiary-fixed': '#FFDEA6',
        'error-container': '#FFDAD6',
        'on-error-container': '#410002',
        'surface-variant': '#F5DDE0',
        'surface-container': '#FCEEEE',
        'surface-container-low': '#FFF8F7',
        'surface-container-high': '#F7E4E4',
      },
      spacing: {
        '18': '4.5rem',
        '22': '5.5rem',
        'margin-mobile': '20px',
        'base': '8px',
        'xs': '4px',
        'sm': '12px',
        'md': '16px',
        'lg': '24px',
        'xl': '32px',
        'gutter': '16px',
      },
      borderRadius: {
        'card': '16px',
        'input': '12px',
        'button': '16px',
      },
      boxShadow: {
        'card': '0 4px 20px rgba(173, 44, 78, 0.08)',
        'soft': '0 2px 8px rgba(173, 44, 78, 0.06)',
      },
      fontSize: {
        'h1': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'h2': ['20px', { lineHeight: '28px', fontWeight: '700' }],
        'body': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'caption': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'button': ['16px', { lineHeight: '1', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
